### ISSUE TITLE
[lab 08] Automatic evaluation of `ddpg.py` InvertedDoublePendulum broken

### ISSUE THREAD

**Issue by paplhjak** [ufal/npfl139#10]
Is it possible that the evaluation of the inverted double pendulum environment is broken? I am receiving returns greater than the specified requirement of 900, but the assignment is evaluated as a failure.

![image](https://github.com/ufal/npfl139/assets/52961799/151c103b-56a3-4042-bd56-6924c62879ae)

**Comment by foxik** [comment]
Sorry, my bad, the required level is actually 9000. I just commited a fix 48759a8a5bbb6c95e678e78f0d59aec0575ae1db and another community-work point is yours :+1:
